### ISSUE TITLE
GitHub Pages publishing behind main?

### ISSUE THREAD

**Issue by czechboy0** [swiftlang/swiftly#182]
Right now, the file https://swiftlang.github.io/swiftly/swiftly-install.sh seems to be out of date from https://github.com/swiftlang/swiftly/blob/main/install/swiftly-install.sh.

Is there a manual step needed here to republish GitHub Pages, so that `curl -L https://swiftlang.github.io/swiftly/swiftly-install.sh | bash` starts working on macOS?

**Comment by sidepelican** [comment]
This is caused by this PR https://github.com/swiftlang/swiftly/pull/173

**Comment by czechboy0** [comment]
@cmcgee1024 can you clarify here?

**Comment by cmcgee1024** [comment]
@czechboy0 the install shell script was being manually published to the GitHub Pages site with each release, sometimes more frequently. We haven't made a new release yet since the migration of swiftly to the swiftlang organization.

In the new release there will be a few changes:
* Everything will be published to swift.org, not the GH pages for this project
* There will no longer be a shell script at all since swiftly will install itself from a trusted binary

**Comment by czechboy0** [comment]
Cool, okay, then there's nothing to change - thanks! 🙏

**Comment by peterkos** [comment]
@cmcgee1024 Is there a timeline / open issue for migrating to swift.org? In particular, because the install script referenced on GH pages (and in the README) is missing the changes from #121, so macOS users need to clone the repo to install, unless I'm missing something?

(and, the website states only Linux is supported, but macOS is also supported 🎉)

**Comment by cmcgee1024** [comment]
@peterkos we're actively working on a few remaining PR's and issues for the next swiftly release, which will be 0.4.0. Also, there are PR's open to update the swift.org website in preparation for the release.

https://github.com/swiftlang/swift-org-website/pull/828
https://github.com/swiftlang/swift-org-website/pull/830
